### ISSUE TITLE
Major: Backstage UI and Menus

### ISSUE THREAD

**Issue by EzraSkwarka** [Berea-CS-Courses/capstone-project-EzraSkwarka#13]
This issue is to track progress on the backstage UI menus. There's an important distinction that this does not mean pause menu as these menus should not cause the game to pause just toggle an overlay.

To resolve this issue there needs to be:
* A toggleable layer that contains a backstage menu on keypress esc
  * This menu should have tabs for:
    * Inventory
    * Overview
      * Should contain info for:
      * Current Relics
      * Current tools and the info for them
      * Gear
    * Structures
      * For now just a tab labeled structures, useability comes later

**Comment by jazzij** [comment]
Based on report out, I think this is the issue you're working on currently? Can you add all the issues to your Project board (on the sidebar of the issue, select a "Project") and move the ones you're working on to "In Progress"
